#!/bin/bash -x

export GO111MODULE=on 
export GOPROXY=https://goproxy.cn
# build webhook
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o cml-engine-resources
# build docker image
docker build --no-cache -t daocloud.io/daocloud/cml-engine-resources:latest .
rm -rf cml-engine-resources

docker push daocloud.io/daocloud/cml-engine-resources:latest
