apiVersion: v1
kind: Service
metadata:
  name: cml-engine-resources-svc
  labels:
    app: cml-engine-resources
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: cml-engine-resources
